---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь форму регистрации
  - Пользователь должен иметь возможность просмотра заказов и только своих
  - При добавлении товара в корзину должна быть возможность указания количества добавляемого товара
  - Должна быть возможность менять количество товара в корзине 
  - При добавлении товара в корзину на карточке товара должно отразиться, что товар лежит в корзине, либо должно появиться модальное окно, информирующее о том, что товар добавлен в корзину
  - Пользователь не должен иметь возможность редактировать, удалять товар в каталоге (вносить изменения)
  - Пользователь должен иметь возможность сортировки товара по цене, по скидке, по рейтингу 
  - Сайт должен иметь форму обратной связи, должна быть указана контактная информация 
  - При удалении товара из корзины, при оформлении заказа должно появляться модальное окно о подтверждении действия 
  - Должна быть возможность перехода в каталог товаров из корзины
  - Пользователь должен иметь возможность оценки товара
  - На сайте должна быть форма для подтверждения согласия на сбор и обработку персональных данных
  - Пустой заказ не должен оформляться
  - В корзине должен отображаться список товаров, их количество и цена, общая стоимость заказа
  - В корзине должна быть возможность выбора товара для оформления
  - Пользователь должен иметь возможность удаления товаров из корзины поштучно и всех сразу
  - При нажатии на логотип в шапке сайта должен происходить переход на главную страницу
  - После оформления заказа корзина должна становиться пустой или с теми товарами, которые не выбрали для оформления
